# -*- coding: utf-8 -*-
"""лабораторная работа 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z7G9OUD1k72e5nODP4Lh3u045joi4UBF
"""

n = int(input('Введи номер месяца:')) #1
if n == 1 :
   print('Январь')
elif n == 2:
   print('Февраль')    
elif n == 3 :
   print('Март')
elif n == 4 :
   print('Апрель')
elif n == 5 :
   print('Май')
elif n == 6 :
   print('Июнь')
elif n == 7 :
   print('Июль')
elif n == 8 :
   print('Август')
elif n == 9 :
   print('Сетябрь')
elif n == 10 :
   print('Октябрь')
elif n ==11 :
   print('Ноябрь')
elif n == 12 :
   print('Август')
else: print('error')

n = int(input('Введи число:')) #2
if n % 2 == 0: print('чётное')
else:
  print('нечётное')

n = int(input('Введи число:')) #3
if n <= 40:
    print('not stonks')
elif n > 40:
    print("stonks")

def is_ears_leap(year): #4
    if (year % 4 == 0) and (0 != year % 100) or (0 == year % 400):
        return('високосный')
    else:
        return('невисокосный')
year = int(input())
is_ears_leap(year)

n = int(input()) #5
def is_prime (n):
  if n % 2 == 0 and n != 2 and n != 0:
    return False
  elif n % 3 == 0 and n != 3:
    return False
  elif n % 5 == 0 and n != 5:
    return False  
  elif n % 7 == 0 and n != 7:
    return False
  else:
    return True
print (is_prime (n))

a = float(input()) #6
b = float(input())

if (a / b>=3.6) or (b > abs((-138 / 2) ** 1.3) and (b < abs(-69 / 28 ** 5.1* 4))):
 a, b = b, a
print(a, b)

a = int(input()) #7
b = int(input())
c = int(input())
d = int(input())
f = int(input())
g = 0
h = 0
j = 0
num = (a,b,c,d,f)
print (set(num), " - уникальные числа")
for i in num:
   if i % 2 == 0: g += 1
   if i < 0: h += 1
   if i > -256 - 1 and i < 1024 + 1: j += 1
print(g, h, j,)

a = int(input('a')) # повышенная сложность
b = int(input('b'))
c = int(input('c'))
s = ((a**2+b**3)/c+3)/4
if s % 2 == 0: print(s,'четное')
else: print(s,'нечетное')

